name: lunar_calendar_converter_new
version: 1.0.0
author: dolaAy<869859518@qq.com>
description: Please read README.md
homepage: "https://github.com/dolaAy/lunar_calendar_converter_new.git"
environment:
  sdk: '>=2.12.0 <3.0.0'